---
title: "Data Import"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```


This document will show how to import data

## Import the FAS Litters CSV
```{r}
litters_df = read_csv("data/FAS_litters.csv")

#janitor gets rid of special characters, replaces spaces with underscores, etc#
litters_df = janitor::clean_names(litters_df)
```

### Look at the dataset

```{r}
 litters_df

head(litters_df)
tail(litters_df,10)
```
 
```{r eval= FALSE}
view(litters_df)
```

## Import FAS pups

```{r}
pups_df = read_csv("data/FAS_pups.csv")

pups_df = janitor::clean_names(pups_df)

pups_df
```

## Look at read_csv options

```{r}
litters_df = 
    read_csv(
        file = "data/FAS_litters.csv",
        col_names = FALSE,
        skip = 1
    )
```


What about the missing data

```{r}
litters_df =
  read_csv(
      file = "data/FAS_litters.csv",
      na = c("NA", "", ".")
  )
```


What if we code `group` as a factor variable?

```{r}
litters_df = 
    read_csv(
        file = "data/FAS_litters.csv",
        na = c("NA", "", "."),
        col_types = cols(
            Group = col_factor()
        ) 
    )
```


## Import an excel file

Import MLD 2011 summary data.

```{r}
mlb_df = read_excel("data/mlb11.xlsx", sheet = "mlb11")
```

## Import SAS data

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```

## Never use read.csv()

```{r}
litters_df = read_csv("data/FAS_litters.csv")
```

Never do this either:
```{r}
#dont use dollar signs#
#look for column that starts with L, you are also taking data out of your dataset, which you should never do#
litters_df$L
```



