---
title: "Data Manipulation"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
```

This document will show how to *manipulate* data.

Import the two datasets that we're going to manipulate

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", "", "."))

litters_df = janitor::clean_names(litters_df)

pups_df = 
  read_csv("data/FAS_pups.csv", na = c("NA", "", "."))

pups_df = janitor::clean_names(pups_df)
```

## 'select'

Use 'select()' to select variables

```{r}
select(litters_df, group, litter_number, gd0_weight)
```

```{r}
select(litters_df, group:gd18_weight)
```


```{r}
#getting rid of pups_survive column#
select(litters_df, -pups_survive)
```

```{r}
#getting rid of every column from group to gd18_weight#
select(litters_df, -group:gd18_weight)
```

```{r}
select(litters_df, starts_with("gd"))

select(litters_df,contains("pups"))
```

```{r}
select(litters_df,GROUP = group)

#keep everything but rename the group to GROUP variable#
rename(litters_df, GROUP = group)

#puts litter_number and gd0_weight first and keep everything#
select(litters_df, litter_number, gd0_weight, everything())

#relocates variables, and keeps everything else#
relocate(litters_df, litter_number, gd0_weight)
```

*Learning assessment*
```{r}
select(pups_df, litter_number, sex, pd_ears)
```



## 'filter'

```{r}
filter(litters_df, gd_of_birth == 20)
filter(litters_df, gd_of_birth == 19)
```

```{r}
filter(litters_df, pups_born_alive > 8)
filter(litters_df, pups_born_alive >= 8)
```

```{r}
filter(litters_df, pups_born_alive != 9)
```

```{r}
filter(litters_df, group == "Low8")

#this group contain either Low7 or Low8#
filter(litters_df, group %in% c("Low7", "Low8"))
```

```{r}
filter(litters_df, group %in% c("Low7", "Low8"), pups_born_alive ==8)
```

```{r}
#filter out rows with any missing data#
drop_na(litters_df)

#filter out rows with any specified missing variable, eg. gd0_weight#
drop_na(litters_df, gd0_weight)
```

*Learning assessment*
```{r}
filter(pups_df, sex == 1)

filter(pups_df, sex == 2, pd_walk < 11)
```



## 'mutate'

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)

mutate(litters_df, sq_pups = pups_born_alive^2)

#overwrite group variable to lowercase "group"#
mutate(litters_df, group = str_to_lower(group))

mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```





## 'arrange'



## PIPING
