---
title: "Tidy Data"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(haven)
library(readxl)
```

This document will

## Pivot Longer

```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
      cols = bdi_score_bl:bdi_score_12m,
      names_to = "visit",
      values_to = "bdi_score",
      names_prefix = "bdi_score_"   #strips all the prefix
  ) |> 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  ) |> 
  relocate(id, visit)
```

Do one more example.

```{r}
litters_df = 
    read_csv("data/FAS_litters.csv", na = c("NA", ".", "")) |> 
    janitor::clean_names() |> 
    pivot_longer(
        cols = gd0_weight:gd18_weight, #name the columns you are interested in between gd0 and gd18 (this is in order, but can also use "starts with..." or "contains...")
        names_to = "gd_time",
        values_to = "weight"
    ) |> 
  mutate(
    gd_time = case_match(
      gd_time, #what variable to look at
        "gd0_weight" ~ 0, #everytime you see gd0_Weight, then replace with 0 
        "gd18_weight" ~ 18
    ))
```

## Pivot wider

Let's make up an analysis result table.

```{r}
analysis_df = 
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time  = c("pre", "post", "pre", "post"),
    mean = c(4, 10, 4.2, 5)
  )
```

Pivot wider for human readability

```{r}
analysis_df |> 
  pivot_wider(
    names_from = time, #which column name are you using
    values_from = mean, #where are the values for that column coming from? the mean variable
  ) |> 
  knitr::kable() #almost always use this as a final step if someone will read the table
```

## Bind tables.

```{r}
fellowship_ring = 
  read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")


two_towers = 
  read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")


return_king = 
  read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")


lotr_df = 
  bind_rows(fellowship_ring, two_towers, return_king) |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = female:male,
    names_to = "sex",
    values_to = "words"
  ) |> 
  relocate(movie) |> #relocates column "movie" to the first column
  mutate(race = str_to_lower(race)) #changes race to lower case
```





